### ISSUE TITLE
CUDA out of memory when running reconstruction

### ISSUE THREAD

**Issue by botaoye** [JingwenWang95/go-surf#1]
Hi, thanks for your great work. I am running the code with RTX2080Ti (11GB memory), when running reconstruction, the constructed `unit_grid` already exceeds the GPU memory limitation. Do you have any suggestions to run it on RTX2080Ti?

https://github.com/JingwenWang95/go-surf/blob/58b1f881abb2017ea95b6811003b3c831cc31411/reconstruct.py#L66

**Comment by JingwenWang95** [comment]
Hi @botaoye, that's weird as we also did experiments on 2080ti, so it shoudn't happen... Can you try reducing `reconstruct_upsample` in the config file to see if you can get something at least? You should be able to find it in `base.yaml` Unfortunately I'm away for a few days, I will have a look when I'm back on Friday.
