### ISSUE TITLE
How can I get color mesh?

### ISSUE THREAD

**Issue by YoungHyun197** [JingwenWang95/go-surf#2]
How Can I get Color mesh? not gray scale
like this url https://jingwenwang95.github.io/go_surf/
Reconstructed mesh with 256^3 grids

can you give me a solution or any code?

**Comment by JingwenWang95** [comment]
Hi @YoungHyun197, sorry for my late response. Unfortunately we didn't include that part of code in this repo, we will add that part in our repo soon. But it is actually very easy to implement, and for now you can try the following:

For the simplist case where the color decoder id only conditioned on features, i.e. set everything to `false` in the config file, what you can do is to simply query the color decoder with the [vertices](https://github.com/JingwenWang95/go-surf/blob/master/reconstruct.py#L80) obtained via marching cubes and then pass them as `vertex_colors` to the [mesh](https://github.com/JingwenWang95/go-surf/blob/master/reconstruct.py#L81). The same process also applies for more sophisticated color decoders, but you will have to query more quantities. Actually in practice we observed that the simplest color decoder yields the best colored mesh, so you can just try with the simplist method first.

**Comment by JingwenWang95** [comment]
I just pushed the code for extracting colored mesh.
