### ISSUE TITLE
out of memory when traing on breakfast_room dataset

### ISSUE THREAD

**Issue by key-destiny** [JingwenWang95/go-surf#4]
Thanks for the amazing work. I tried to run `python train.py --scene grey_white_room  --exp_name test` on A100@80G and failed with CUDA out of memory. The result was the same when the `batch_size` was set to 10. When I set the `voxel_sizes` to `[0.06, 0.12, 0.48, 1.92]`, 18GB of GPU memory was used and the mesh extracted was not good as the result in the paper. I have also tried the example [here](https://github.com/tymoteuszb/smooth-sampler#readme) and more than 1GB of GPU memory was used. Is that normal? Is there any suggestion for me to reproduce the results in the paper? Thanks again for your open work.

**Comment by JingwenWang95** [comment]
Hi @key-destiny! Thanks for your interest! That's really weird... Actually we've done all our experiments with a single RTX2080ti with only 11GB memory, and specifically for grey_white_room with our default setting ([0.03, 0.06, 0.24, 0.96] voxel sizes and batch_size=6144) the GPU memory required for training shouldn't exceed 5GB. It's really weird that you even need 18GB for reduced setting.

As for reproducing the results, we have done extensively tesing on various kinds of hardwares (2080ti, 3090, etc) before releasing the code but we never experienced such weird thing. Maybe can you provide more information on how you ran your experiments? Did you change anything in the code?

**Comment by key-destiny** [comment]
Thanks for your reply!

> Did you change anything in the code?

 I have changed nothing expect for the `datasets_dir`, `batch_size` and `voxel_sizes` in the base.yaml.

> Maybe can you provide more information on how you ran your experiments?

I ran my experiments on Ubantu with pytorch 1.11.0+cuda113 and CUDA 11.3, and by the way, every checkpoint saved by the model used 2.4 GB memory.

> I have also tried the example [here](https://github.com/tymoteuszb/smooth-sampler#readme) and more than 1GB of GPU memory was used. Is that normal?

Have you tracked the memory usage over the example in smooth-sampler?

**Comment by JingwenWang95** [comment]
That's really weird, we've never seen such big checkpoint size even for the largesr scene in our experiments. You can find the saved model size in our paper's supplementary (and times 3 if you also save the optimizer state). 

I haven't checked the memory usage in that example, but in any ways it shouldn't consume memory in the order of 1GB: Basically it creates only two `2x3x11` grids with feature dimension of 2 and query them with `2x1x5=10` points each...

Sorry, I really have no idea what happened to your machine and I don't have an A100 to test with. I would suggest you test with an alternative machine (a single 2080ti GPU with 32GB RAM will definitely enough) and see if the problem still persists.

**Comment by key-destiny** [comment]
> That's really weird, we've never seen such big checkpoint size even for the largesr scene in our experiments. You can find the saved model size in our paper's supplementary (and times 3 if you also save the optimizer state).
> 
> I haven't checked the memory usage in that example, but in any ways it shouldn't consume memory in the order of 1GB: Basically it creates only two `2x3x11` grids with feature dimension of 2 and query them with `2x1x5=10` points each...
> 
> Sorry, I really have no idea what happened to your machine and I don't have an A100 to test with. I would suggest you test with an alternative machine (a single 2080ti GPU with 32GB RAM will definitely enough) and see if the problem still persists.


Thank you for your quick reply and I will make an attempt.

**Comment by JingwenWang95** [comment]
I'm closing it now as there is no updates for a while. Feel free to reopen it afterwards!
