### ISSUE TITLE
About setting scene bounds

### ISSUE THREAD

**Issue by f745311** [JingwenWang95/go-surf#8]
Hi, thanks for sharing such a awesome work. And I wonder how do I set the "scene bounds" at get_scene_bounds.py with other custom datasets? and what is the exact meanings about x_min, x_max, y_min, y_max, z_min and z_max?

**Comment by JingwenWang95** [comment]
Hi @f745311! Those parameters are just the min/max values of the scene bound along x/y/z dimension. For scannet we compute the scene bound by computing those min/max values of gt mesh vertices and added a small margin (around 0.2m). Anyways it's just a bounding box you define for ypur region of interests.

**Comment by f745311** [comment]
Do you have any advice that if I using some own datasets and without gt mesh ?

**Comment by JingwenWang95** [comment]
If you have camera poses and depth, you can run TSDF-fusion and find the scene bound. But anyways anything that encloses the region of interest of the scene will be enough.
