### ISSUE TITLE
result of thin_geometry scene

### ISSUE THREAD

**Issue by XuqianRen** [JingwenWang95/go-surf#9]
Hi, I want to ask the exact parameters you used to train the thin_geometry scene, because when I used the thin_geometry.yaml in the configs file , the result I got is {"Acc": 0.009974530630902648, "Comp": 0.02259144094982974, "C-L1": 0.016282985790366196, "NC": 0.9041278715097523, "F-score": 0.9246799075219604}. The results, especially the F-score,  are worse than the result you reported on your paper. But for the other scenes, the results are similar.

**Comment by JingwenWang95** [comment]
Hi @XuqianRen! Did you switch off the `remove_missing_depth` flag when running culling for thin_geometry? For that specific scene you need to switch off that flag because the thin structures don't have any depth measurement and thus will all be removed.

**Comment by XuqianRen** [comment]
got it, thank you
